pipeline {
  agent any

  environment {
    IMAGE_NAME = "taemin0323/vanish-fe"
    CONTAINER_NAME = "vanish-fe"
    NETWORK = "vanish-net"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Docker Build & Push') {
      steps {
        // mapbox-token과 imp-code 두 가지 secret 텍스트를 함께 사용
        withCredentials([
          string(credentialsId: 'mapbox-token', variable: 'MAPBOX_TOKEN'),
          string(credentialsId: 'imp-code', variable: 'VITE_IMP_CODE')
        ]) {
          script {
            docker.withRegistry('https://index.docker.io/v1/', 'Docker-Hub') {
              sh """
              docker build -t ${IMAGE_NAME}:latest \\
                --build-arg VITE_MAPBOX_ACCESS_TOKEN=${MAPBOX_TOKEN} \\
                --build-arg VITE_IMP_CODE=${VITE_IMP_CODE} \\
                FE/front
              docker push ${IMAGE_NAME}:latest
              """
            }
          }
        }
      }
    }

    stage('Deploy') {
      steps {
        sh """
        docker rm -f ${CONTAINER_NAME} || true
        docker pull ${IMAGE_NAME}:latest
        docker run -d --name ${CONTAINER_NAME} \\
          --network ${NETWORK} \\
          -p 80:80 -p 443:443 \\
          -v /root/nginx/cert/live:/etc/letsencrypt/live \\
          -v /root/nginx/cert/archive:/etc/letsencrypt/archive \\
          -v /root/nginx/cert/renewal:/etc/letsencrypt/renewal \\
          ${IMAGE_NAME}:latest
        """
      }
    }
  }
}
